name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment:
      name: Production
    env:
      API_KEY: ${{ vars.API_KEY }}
      AUTH_DOMAIN: ${{ vars.AUTH_DOMAIN }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ vars.MESSAGING_SENDER_ID }}
      APP_ID: ${{ vars.APP_ID }}
      MEASUREMENT_ID: ${{ vars.MEASUREMENT_ID }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
