name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment:
      name: Production
    env:
      REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
      ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
      OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}


    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
